name: "example"

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    paths:
      - 'example/**/*.dart'
      - 'example/**/*.yaml'
      - .github/workflows/_base*.yaml
      - .github/workflows/example.yaml
  release:
    types: [published]

jobs:
  is-flutter:
    uses: ./.github/workflows/_base-has_flutter.yaml
    with:
      path: '.'

  dart:
    needs: is-flutter
    if: needs.is-flutter.outputs.is_flutter == '0'
    strategy:
      matrix:
        example: [ editor ]
    name: "${{ matrix.example }}"
    uses: ./.github/workflows/_base-dart.yaml
    with:
      path: "example/${{ matrix.example }}"

  flutter:
    needs: is-flutter
    if: needs.is-flutter.outputs.is_flutter == '1'
    strategy:
      matrix:
        example: [ editor ]
    name: "${{ matrix.example }}"
    uses: ./.github/workflows/_base-flutter.yaml
    with:
      path: "example/${{ matrix.example }}"